### ISSUE TITLE
[patch] a diff to fix some little issues on Linux

### ISSUE THREAD

**Issue by ebachard** [arionik/avilib#1]
Hi,

Thanks a lot for sharing your code. I didn't learn it much yet, but I had to fix some little build issues on Linux, and instead of fork + PR, I simply created a patch on gist. If the change are ok for you, put it under the MIT license, or the license you need, and do what you want with it :-)

For the record, the build issues were: 
- breakage caused by wrong directory ../build  (correct was  ./build), avoiding ibavi64.a and aviapp binaries to be created  (changes done in the Makefile)
- a warning caused by a wrong format type in a string => I added a new define, when OS is Linux (reader.cpp)
- added a $(OS_CXXFLAGS) at build time, to improve portability (Makefile)
- warning caused by unused variable (z, line around 319)

See : https://gist.github.com/ebachard/3ed2b0720830b56edee341547ba29fed

Thanks

**Comment by arionik** [comment]
Hey, thanks!
I partly applied it to master; note the whole thing is a bit improvised, I just needed a free avi lib for my video only player.
Cheers!
